### ISSUE TITLE
instadm.py err: index out of range

### ISSUE THREAD

**Issue by SkyLakeRT** [CamTosh/instagram-bot-dm#2]
Hi, everyone!

I have this error 

i use this DM bot with INSTAPY

MY START SCRIPT:
```
from instadm import InstaDM

if __name__ == '__main__':
	# Auto login
	insta = InstaDM(
		username='my_login',
		password='my_passwd',
		headless=False,
		instapy_workspace='/home/skylakert/'
	)


	#insta.login
```

**Comment by SkyLakeRT** [comment]
I have instapy version Version: 0.6.9

**Comment by SkyLakeRT** [comment]
i have error before, i change 
1. sqlite request [invalid syntax]
2. var - CONN [var CONN is not difined]

1 + 2:
after /if self.instapy_workspace != None:/
#i change to 
```
self.cursor = self.conn.cursor()
cursor = self.conn.execute("SELECT count(*) FROM sqlite_master WHERE type='table' AND name='message';")
self.conn.execute("CREATE TABLE 'message' ('username' TEXT NOT NULL UNIQUE, 'message' TEXT DEFAULT NULL, 'sent_message_at' TIMESTAMP);")
```

**Comment by SkyLakeRT** [comment]
I am check this code,
have error this string
after /def login(self, username, password):/
`self.driver.find_elements_by_css_selector(self.selectors['home_to_login_button'])[0].click()`

but i don't know how to solved this issue. Help me please!

**Comment by SkyLakeRT** [comment]
i have this err from atom editor + debugger
![image](https://user-images.githubusercontent.com/28181603/87126883-51d32680-c2d0-11ea-89aa-4672cc4c0e46.png)
![image](https://user-images.githubusercontent.com/28181603/87126938-6a434100-c2d0-11ea-9ebf-9f38b9edc0f3.png)

**Comment by SkyLakeRT** [comment]
////////////////////////////////////
OR RUN THIS
//////////////////////////////////////

RUN WITHOUT INSTAPY
ONLY THIS REPO

```
skylakert@nupc:~/Desktop/developing/atom/IG_SYSTEM/instapy/instapy-quickstart$ python3.7 test_DM-external.py 
__init__
login
__randomSleep__
ERROR:root:list index out of range
sendMessage
Traceback (most recent call last):
  File "test_DM-external.py", line 11, in <module>
    insta.sendMessage(user='xford.tech', message='jast for testingggggggg')
  File "/home/skylakert/Desktop/developing/atom/IG_SYSTEM/instapy/instapy-quickstart/instadm.py", line 89, in sendMessage
    self.driver.find_element_by_name(self.selectors['search_user']).send_keys(user)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 496, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="queryBox"]"}
  (Session info: chrome=83.0.4103.116)
```

**Comment by SkyLakeRT** [comment]
__init__
login
__randomSleep__
this print() function, i have added this manually

**Comment by edohub** [comment]
I've got the same problem, but I couldn't understand from your posts if you figured out how to solve that or not. I do not understand why the list index seems to be out of range, I do not see any problem with lists apparently

**Comment by SkyLakeRT** [comment]
> I've got the same problem, but I couldn't understand from your posts if you figured out how to solve that or not. I do not understand why the list index seems to be out of range, I do not see any problem with lists apparently

No, I search different bot, only direct message function
https://github.com/b31ngD3v/instagram-auto-dm

**Comment by secretshardul** [comment]
Same issue. The issue seems to be with `queryBox` selector, I can't find it the instagram website.
```
Unable to locate element: {"method":"css selector","selector":"[name="queryBox"]"}
```

**Comment by coding-ty** [comment]
It looks as if your webdriver is version 83.X.X.X. Check your chrome to see if the versions match.
